# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FKHHKMG4bkE9fUgLjKkvRbwTiTDogGOJ
"""

i=1
while (i<=100):
  if i%2==0 and i%5!=0:

    print(i)
  i+=1